# https://medium.com/@mrjohnkilonzi/how-to-deploy-your-vuejs-using-github-actions-on-firebase-hosting-a667aabd88f7

name: Build and deploy Node.js app to Firebase Hosting for character-book

on:
  push:
    branches:
      - main

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
      # Runs a single command using the runners shell
      # And of course we need to goto our functions folder to deploy
      - name: Install npm packages in Functions
        run: |
          cd functions
          npm install
      # Deploying the functions to firebase
      - name:  Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
            args: deploy --only functions
        env:
              FIREBASE_TOKEN: ${{ secrets.FirebaseDeploy }}
